import { CreateClientDTO } from "../client/dto/create-client.dto";
import { EnterpriseLegalForm, LeadStatus, LeadType } from "../generated/prisma/enums";

// -
interface ClientType {
    type: "PARTICULIER" | "ENTREPRISE";
    country: string;
    address: string;
    contactName: string;
    phone: string;
    email: string;
    companyName: string | null;
    companyLegalForm: EnterpriseLegalForm | null;
    industry: string | null;
    tenantId: number;
}


export const CLIENT_SEED: ClientType[] = [
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Plateau",
    contactName: "Amadou Ndiaye",
    phone: "770000001",
    email: "contact1@batisen.sn",
    companyName: "BatiSen",
    companyLegalForm: "SARL",
    industry: "Construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Rufisque",
    contactName: "Fatou Diop",
    phone: "770000002",
    email: "fatou2@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Thiès",
    contactName: "Moussa Ba",
    phone: "770000003",
    email: "contact3@senbuild.sn",
    companyName: "SenBuild",
    companyLegalForm: "SA",
    industry: "BTP",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Mbour",
    contactName: "Awa Fall",
    phone: "770000004",
    email: "awa4@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Saint-Louis",
    contactName: "Cheikh Sarr",
    phone: "770000005",
    email: "contact5@afribat.sn",
    companyName: "AfriBat",
    companyLegalForm: "SAS",
    industry: "Génie civil",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Kaolack",
    contactName: "Khady Sy",
    phone: "770000006",
    email: "khady6@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Diamniadio",
    contactName: "Ibrahima Gueye",
    phone: "770000007",
    email: "contact7@teranga.sn",
    companyName: "Teranga TP",
    companyLegalForm: "SUARL",
    industry: "Travaux publics",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Ziguinchor",
    contactName: "Mariama Cissé",
    phone: "770000008",
    email: "mariama8@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Touba",
    contactName: "Ousmane Mbaye",
    phone: "770000009",
    email: "contact9@construct.sn",
    companyName: "Construct Plus",
    companyLegalForm: "SNC",
    industry: "Architecture",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Louga",
    contactName: "Ndeye Kane",
    phone: "770000010",
    email: "ndeye10@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Yoff",
    contactName: "Babacar Faye",
    phone: "770000011",
    email: "contact11@urban.sn",
    companyName: "Urban Habitat",
    companyLegalForm: "SARL",
    industry: "Immobilier",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Kolda",
    contactName: "Astou Diallo",
    phone: "770000012",
    email: "astou12@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Almadies",
    contactName: "Seydou Tall",
    phone: "770000013",
    email: "contact13@atlas.sn",
    companyName: "Atlas Ingénierie",
    companyLegalForm: "SA",
    industry: "Ingénierie",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Fatick",
    contactName: "Rokhaya Seck",
    phone: "770000014",
    email: "rokhaya14@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Thiès",
    contactName: "Alioune Sow",
    phone: "770000015",
    email: "contact15@elite.sn",
    companyName: "Elite BTP",
    companyLegalForm: "SCS",
    industry: "Construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Kébémer",
    contactName: "Mame Niang",
    phone: "770000016",
    email: "mame16@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Liberté 6",
    contactName: "Lamine Dieng",
    phone: "770000017",
    email: "contact17@horizon.sn",
    companyName: "Horizon Bâtiment",
    companyLegalForm: "SAS",
    industry: "BTP",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Joal",
    contactName: "Penda Gaye",
    phone: "770000018",
    email: "penda18@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Diamniadio",
    contactName: "Modou Thiam",
    phone: "770000019",
    email: "contact19@innov.sn",
    companyName: "Innov TP",
    companyLegalForm: "SARL",
    industry: "Travaux publics",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Matam",
    contactName: "Aissatou Ly",
    phone: "770000020",
    email: "aissatou20@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Fann",
    contactName: "Serigne Diouf",
    phone: "770000021",
    email: "contact21@prestige.sn",
    companyName: "Prestige Habitat",
    companyLegalForm: "SA",
    industry: "Immobilier",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Tambacounda",
    contactName: "Yacine Camara",
    phone: "770000022",
    email: "yacine22@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Hann",
    contactName: "Abdou Karim",
    phone: "770000023",
    email: "contact23@delta.sn",
    companyName: "Delta Construction",
    companyLegalForm: "SUARL",
    industry: "Construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Bargny",
    contactName: "Sokhna Ndour",
    phone: "770000024",
    email: "sokhna24@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Mbour",
    contactName: "El Hadji Sylla",
    phone: "770000025",
    email: "contact25@ocean.sn",
    companyName: "Océan BTP",
    companyLegalForm: "SARL",
    industry: "Génie civil",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Richard-Toll",
    contactName: "Coumba Sow",
    phone: "770000026",
    email: "coumba26@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Kaolack",
    contactName: "Papa Diallo",
    phone: "770000027",
    email: "contact27@sahel.sn",
    companyName: "Sahel TP",
    companyLegalForm: "SNC",
    industry: "Travaux publics",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Podor",
    contactName: "Dieynaba Fall",
    phone: "770000028",
    email: "dieynaba28@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Médina",
    contactName: "Mamadou Lô",
    phone: "770000029",
    email: "contact29@vision.sn",
    companyName: "Vision Bâtiment",
    companyLegalForm: "SAS",
    industry: "Architecture",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Saly",
    contactName: "Aminata Ba",
    phone: "770000030",
    email: "aminata30@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Touba",
    contactName: "Daouda Sarr",
    phone: "770000031",
    email: "contact31@probat.sn",
    companyName: "ProBat",
    companyLegalForm: "SA",
    industry: "Construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Kaffrine",
    contactName: "Bineta Cissé",
    phone: "770000032",
    email: "bineta32@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Thiès",
    contactName: "Issa Ndiaye",
    phone: "770000033",
    email: "contact33@eco.sn",
    companyName: "Eco Chantier",
    companyLegalForm: "SARL",
    industry: "Éco-construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Diourbel",
    contactName: "Nafissatou Seck",
    phone: "770000034",
    email: "nafissatou34@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Ngor",
    contactName: "Jean Pierre Fall",
    phone: "770000035",
    email: "contact35@global.sn",
    companyName: "Global Infra",
    companyLegalForm: "SAS",
    industry: "Infrastructures",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Linguère",
    contactName: "Adama Thiam",
    phone: "770000036",
    email: "adama36@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Kolda",
    contactName: "Mor Ndiaye",
    phone: "770000037",
    email: "contact37@africa.sn",
    companyName: "Africa Habitat",
    companyLegalForm: "SUARL",
    industry: "Immobilier",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Kédougou",
    contactName: "Oumy Diallo",
    phone: "770000038",
    email: "oumy38@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Sacré-Cœur",
    contactName: "Tidiane Gaye",
    phone: "770000039",
    email: "contact39@avenir.sn",
    companyName: "Avenir BTP",
    companyLegalForm: "SARL",
    industry: "BTP",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Foundiougne",
    contactName: "Maimouna Sy",
    phone: "770000040",
    email: "maimouna40@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Diamniadio",
    contactName: "Habib Faye",
    phone: "770000041",
    email: "contact41@capital.sn",
    companyName: "Capital TP",
    companyLegalForm: "SA",
    industry: "Travaux publics",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Bambey",
    contactName: "Mouhamed Kane",
    phone: "770000042",
    email: "mouhamed42@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Saint-Louis",
    contactName: "Saliou Mbengue",
    phone: "770000043",
    email: "contact43@sunu.sn",
    companyName: "Sunu Construction",
    companyLegalForm: "SNC",
    industry: "Construction",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Oussouye",
    contactName: "Fama Cissé",
    phone: "770000044",
    email: "fama44@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Ouakam",
    contactName: "Matar Diallo",
    phone: "770000045",
    email: "contact45@prime.sn",
    companyName: "Prime Ingénierie",
    companyLegalForm: "SAS",
    industry: "Ingénierie",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Guédiawaye",
    contactName: "Hawa Ndiaye",
    phone: "770000046",
    email: "hawa46@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Rufisque",
    contactName: "Souleymane Ba",
    phone: "770000047",
    email: "contact47@rex.sn",
    companyName: "Rex BTP",
    companyLegalForm: "SARL",
    industry: "Génie civil",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Pikine",
    contactName: "Adji Sarr",
    phone: "770000048",
    email: "adji48@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
  {
    type: "ENTREPRISE",
    country: "Sénégal",
    address: "Dakar, Mermoz",
    contactName: "Ibra Seck",
    phone: "770000049",
    email: "contact49@nova.sn",
    companyName: "Nova Habitat",
    companyLegalForm: "SA",
    industry: "Immobilier",
    tenantId: 1,
  },
  {
    type: "PARTICULIER",
    country: "Sénégal",
    address: "Tivaouane",
    contactName: "Seynabou Ly",
    phone: "770000050",
    email: "seynabou50@mail.sn",
    companyName: null,
    companyLegalForm: null,
    industry: null,
    tenantId: 1,
  },
];

export const generateLeads = (count = 100) => {
  const services = [
    "Construction villa",
    "Immeuble R+4",
    "Rénovation bureaux",
    "Voirie & assainissement",
    "Extension bâtiment",
    "Génie civil",
    "Charpente métallique",
    "Finition intérieure",
  ];

  const statuses = [
    LeadStatus.OPENED,
    LeadStatus.LOST,
    LeadStatus.WON,
  ];

  const types = [
    LeadType.OFFER,
    LeadType.PROSPECTION,
  ];

  return Array.from({ length: count }, () => {
    const amountHT = Math.floor(Math.random() * 45_000_000) + 5_000_000;
    const amountTVA = Math.round(amountHT * 0.18);

    return {
      service: services[Math.floor(Math.random() * services.length)],
      type: types[Math.floor(Math.random() * types.length)],
      amountHT,
      amountTVA,
      amountTTC: amountHT + amountTVA,
      deadline: new Date(
        2026,
        Math.floor(Math.random() * 12),
        Math.floor(Math.random() * 28) + 1
      ),
      status: statuses[Math.floor(Math.random() * statuses.length)],
      clientId: Math.floor(Math.random() * 50) + 1,
      tenantId: 1,
      authorId: 1,
    };
  });
};